name: Gradle Dependency Submission

on:
  push:
    branches: [main, master]

jobs:
  dependency-submission:
    uses: Widen/github-actions/.github/workflows/gradle-dependency-submission-workflow.yml@v1
    secrets: inherit
